version: '3'

services:
  qzws:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qzws
    container_name: qzws
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:18000:18000"
#    volumes:
#      - "/data/wwwlogs/qzws_log/:/data/app/qzws/runtime/log/access"

