version: "3"
services:
  qzmsg:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qzmsg
    container_name: qzmsg
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:18100:18100"
#    volumes:
#      - "/data/app/qzmsg/config/:/data/app/qzmsg/config/"

#volumes:
