apiVersion: apps/v1
kind: Deployment
metadata:
  name: qzorder
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    matchLabels:
      app: qzorder
  template:
    metadata:
      labels:
        app: qzorder
    spec:
      containers:
      - name: qzorder
        # image: registry.cn-shanghai.aliyuncs.com/qizuang/qzorder:master-040ce9e
        image: <K8S_IMAGE>
        imagePullPolicy: Always
        # command: [ "echo", "SUCCESS" ]
        ports:
        - containerPort: 18800
          name: 18800tcp00
          protocol: TCP
        # envFrom:
        # - configMapRef:
        #     name: env-app-config
        volumeMounts:
          - mountPath: /data/app/qzorder/config
            name: vol1
      imagePullSecrets:
      - name: "container-registry-a"
      volumes:
        - configMap:
            defaultMode: 256
            items:
              - key: qzorder
                path: config.toml
            name: app-config
            optional: false
          name: vol1

---
kind: Service
apiVersion: v1
metadata:
  name: qzorder
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    app: qzorder
  ports:
    - protocol: TCP
      port: 18800
      targetPort: 18800
  type: ClusterIP