version: "3.1"
services:
  #搜索
  search:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/search
    container_name: search
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:16000:16000"
    #volumes:
    #  - "./config/:/data/app/search/config/"
