version: "3"
services:
#抽词
  chouci.service:
    build: .
    image:  registry.cn-shanghai.aliyuncs.com/qizuang/chouci.service
    container_name: chouci.service
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:11000:11000"
