version: "3"
services:
  qz-user-cp-ui:
    build: .
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qz-user-cp-ui
    container_name: qz-user-cp-ui
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:20008:80"
