# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# --------------- V1 ----------------- #
### 签名 列表
POST http://127.0.0.1:12000/v1/send
Accept: application/json

# --------------- V1管理后台 ----------------- #

### 签名 列表
GET http://127.0.0.1:12000/v1/admin/sign/list
Accept: application/json

### 签名 增加
GET http://127.0.0.1:12000/v1/admin/sign/add
Accept: application/json

### 签名 删除
GET http://127.0.0.1:12000/v1/admin/sign/del
Accept: application/json







### Get request with a header
GET https://httpbin.org/ip
Accept: application/json

### Get request with parameter
GET https://httpbin.org/get?show_env=1
Accept: application/json

### Get request with environment variables
GET {{host}}/get?show_env={{show_env}}
Accept: application/json

### Get request with disabled redirects
# @no-redirect
GET http://httpbin.org/status/301

###
