version: "3.1"
services:
  #------ admin 管理后台 API ------#
  admin-api.service:
    build: .
    image: registry.cn-shanghai.aliyuncs.com/qizuang/admin-api.service
    container_name: admin-api.service
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:20000:20000"
#    volumes:
#      - "./config:/data/app/admin-api/config/"
