apiVersion: apps/v1
kind: Deployment
metadata:
  name: qzws
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    matchLabels:
      app: qzws
  template:
    metadata:
      labels:
        app: qzws
    spec:
      imagePullSecrets:
        - name: "container-registry-a"
      containers:
        - name: qzws
          # image: registry.cn-shanghai.aliyuncs.com/qizuang/qzws:master-040ce9e
          image: <K8S_IMAGE>
          imagePullPolicy: Always
          # command: [ "echo", "SUCCESS" ]
          ports:
            - name: qzws
              containerPort: 18000
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          # envFrom:
          # - configMapRef:
          #     name: env-app-config
          volumeMounts:
            - mountPath: /data/app/qzws/config
              name: app-volume
            - name: ssl-volume
              mountPath: /etc/nginx/ssl
      volumes:
        - name: app-volume
          configMap:
            defaultMode: 256
            items:
              - key: qzws
                path: config.toml
            name: app-config
            optional: false
        - name: ssl-volume
          secret:
            secretName: app-ssl

---
kind: Service
apiVersion: v1
metadata:
  name: qzws
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    app: qzws
  ports:
    - name: qzws
      protocol: TCP
      port: 18000
      targetPort: 18000
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP