version: "3.1"
services:
  #短信
  qzpnp:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qzpnp
    container_name: qzpnp
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:18600:18600"
    #volumes:
    #  - "./config/:/data/app/qzpnp/config/"
