[Yunrongt]
    [Yunrongt.normal]
        url = "http://47.98.61.138:9001/smsSend.do"
        username = "qzwhy"
        password = "cS7oJ9oZ"
    [Yunrongt.yx]
        Url = "http://47.98.61.138:9001/smsSend.do"
        Username = "qzwyx"
        Password = "yU9xJ8bD"

