apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenci
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    matchLabels:
      app: fenci
  template:
    metadata:
      labels:
        app: fenci
    spec:
      imagePullSecrets:
      - name: container-registry-a
      containers:
      - name: fenci
        # image: registry.cn-shanghai.aliyuncs.com/qizuang/fenci:master-040ce9e
        image: <K8S_IMAGE>
        imagePullPolicy: Always
        # command: [ "echo", "SUCCESS" ]
        ports:
        - containerPort: 11001
          name: 11001tcp02
          protocol: TCP
        # envFrom:
        # - configMapRef:
        #     name: env-app-config
      imagePullSecrets:
      - name: "container-registry-a"

---
kind: Service
apiVersion: v1
metadata:
  name: fenci
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    app: fenci
  ports:
    - protocol: TCP
      port: 11001
      targetPort: 11001
  type: ClusterIP