version: "3.1"
services:
  #短信
  qzsms:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qzsms
    container_name: qzsms
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:12000:12000"
    #volumes:
    #  - "./config/:/data/app/qzsms/config/"
