version: "3"
services:
#------ admin 管理后台 UI ------#
  168sales-admin-ui:
    build: .
    image: registry.cn-shanghai.aliyuncs.com/qizuang/168sales-admin-ui
    container_name: 168sales-admin-ui
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:20860:80"
