version: "3"
services:
#------ admin 管理后台 UI ------#
  admin-ui.service:
    build: .
    image: registry.cn-shanghai.aliyuncs.com/qizuang/admin-ui.service
    container_name: admin-ui.service
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:20001:80"
