version: "3.1"
services:
  #短信
  qzorder:
    build: ./
    image: registry.cn-shanghai.aliyuncs.com/qizuang/qzorder
    container_name: qzorder
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "0.0.0.0:18800:18800"
    #volumes:
    #  - "./config/:/data/app/qzorder/config/"
