version: "3.1"
services:
  #passport
  passport:
    build: ./
    container_name: passport
    image: registry.cn-shanghai.aliyuncs.com/qizuang/passport
    restart: always
#    networks:
#      - font-network
#      - back-network
    ports:
      - "0.0.0.0:19000:19000"
    #network_mode: host
#    volumes:
#      - "./config/:/data/app/passport/config/"


#networks:
#  font-network:
#    driver: bridge
#  back-network:
#    driver: bridge