apiVersion: apps/v1
kind: Deployment
metadata:
  name: qz-user-cp-ui
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    matchLabels:
      app: qz-user-cp-ui
  template:
    metadata:
      labels:
        app: qz-user-cp-ui
    spec:
      imagePullSecrets:
        - name: "container-registry-a"
      containers:
        - name: qz-user-cp-ui
          # image: registry.cn-shanghai.aliyuncs.com/qizuang/qz-user-cp-ui:master-040ce9e
          image: <K8S_IMAGE>
          imagePullPolicy: Always
          # command: [ "echo", "SUCCESS" ]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          # envFrom:
          # - configMapRef:
          #     name: env-app-config
          volumeMounts:
            - name: ssl-volume
              mountPath: /etc/nginx/ssl
      volumes:
        - name: ssl-volume
          secret:
            secretName: app-ssl

---
kind: Service
apiVersion: v1
metadata:
  name: qz-user-cp-ui
  # namespace: development
  namespace: <K8S_NAMESPACE>
spec:
  selector:
    app: qz-user-cp-ui
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP
